// The weighted city list, in source order. A weight is the size of the city's
// range on the source list's 1 to 348 roll. Names are the source's, except that
// its "Cincinatti" and "Witchita" are spelled correctly here.

export const CITIES: { name: string; weight: number }[] = [
  { name: "New York", weight: 42 },
  { name: "Los Angeles", weight: 19 },
  { name: "Chicago", weight: 16 },
  { name: "Dallas - Fort Worth", weight: 16 },
  { name: "Phoenix", weight: 14 },
  { name: "Houston", weight: 12 },
  { name: "Philadelphia", weight: 10 },
  { name: "Denver", weight: 10 },
  { name: "San Diego", weight: 8 },
  { name: "Orange County (Long Beach)", weight: 8 },
  { name: "San Antonio", weight: 7 },
  { name: "Charlotte", weight: 7 },
  { name: "San Francisco", weight: 7 },
  { name: "Washington DC", weight: 7 },
  { name: "Las Vegas", weight: 7 },
  { name: "Minneapolis / St Paul", weight: 7 },
  { name: "Seattle", weight: 6 },
  { name: "Boston", weight: 6 },
  { name: "Detroit", weight: 6 },
  { name: "Miami", weight: 6 },
  { name: "Jacksonville", weight: 5 },
  { name: "San Jose", weight: 5 },
  { name: "Columbus", weight: 5 },
  { name: "Indianapolis", weight: 5 },
  { name: "Milwaukee", weight: 5 },
  { name: "Atlanta", weight: 5 },
  { name: "Tampa", weight: 5 },
  { name: "Austin", weight: 4 },
  { name: "Nashville", weight: 4 },
  { name: "Oklahoma City", weight: 4 },
  { name: "Baltimore", weight: 4 },
  { name: "Sacramento", weight: 4 },
  { name: "Kansas City", weight: 4 },
  { name: "Cleveland", weight: 4 },
  { name: "Newark (Jersey City)", weight: 4 },
  { name: "Pittsburgh", weight: 4 },
  { name: "Louisville", weight: 3 },
  { name: "Portland", weight: 3 },
  { name: "Memphis", weight: 3 },
  { name: "Raleigh", weight: 3 },
  { name: "New Orleans", weight: 3 },
  { name: "Cincinnati", weight: 3 },
  { name: "Saint Louis", weight: 3 },
  { name: "Buffalo", weight: 3 },
  { name: "El Paso", weight: 2 },
  { name: "Albuquerque", weight: 2 },
  { name: "Fresno", weight: 2 },
  { name: "Tucson", weight: 2 },
  { name: "Omaha", weight: 2 },
  { name: "Virginia Beach", weight: 2 },
  { name: "Oakland", weight: 2 },
  { name: "Orlando", weight: 2 },
  { name: "Bakersfield", weight: 1 },
  { name: "Tulsa", weight: 1 },
  { name: "Wichita", weight: 1 },
  { name: "Honolulu", weight: 1 },
  { name: "Lexington KY", weight: 1 },
  { name: "Corpus Christi", weight: 1 },
  { name: "Greensboro", weight: 1 },
  { name: "Lincoln NE", weight: 1 },
  { name: "Anchorage", weight: 1 },
  { name: "Madison WI", weight: 1 },
  { name: "Reno", weight: 1 },
  { name: "Fort Wayne", weight: 1 },
  { name: "Lubbock", weight: 1 },
  { name: "Laredo", weight: 1 },
  { name: "Toledo", weight: 1 },
  { name: "Winston-Salem", weight: 1 },
];
