// CE v1.5 training camp step 8: Table U, Unexpected Events (Appendix A, pages
// 26 and 27). Rolled as 2d6 with one die the tens and the other the ones, so
// the keys are 11 to 66. Kept as printed.

export const TABLE_U: Record<string, string> = {
  "11": "Star defensive lineman suffers season ending injury in training camp! Team loses any PUNISHING quality and gains MILD• quality (reduce to MILD if already MILD•). Ignore if already MILD.",
  "12": "Late free agent singing of veteran wide-receiver is an immediate boost to the offense. Team’s offensive strength is increased one half quality. (e.g. DULL• to average, PROLIFIC• to PROLIFIC, etc.). Ignore if already PROLIFIC.",
  "13": "Starting quarterback suffers season ending injury in pre-season game! Team’s offense strength reduced to DULL• (reduce to DULL if already DULL•). Ignore if already DULL.",
  "14": "Free Agent signing of popular defensive-end improves team’s pass rush. Team loses any MILD quality and gains PUNISHING• (increase to PUNISHING if already PUNISHING•). Ignore if already PUNISHING.",
  "15": "Unexpected skill shown by late-round offensive lineman. Team loses any POROUS quality and gains SOLID• (increase to SOLID if already SOLID•). Ignore if already SOLID.",
  "16": "If Head Coach rating is B or better, team loses any UNDISCIPLINED qualities and gains DISCIPLINED for both offense and defense. Otherwise, team loses any DISCIPLINED qualities and gains UNDISCIPLINED for both offense and defense.",
  "21": "New special teams coach improves place-kicker’s mechanics. Increase kickers success range for both extra points and field goals by 2 steps. (e.g. 11-56 would increase to 11-62)",
  "22": "Renewed focus on forcing turnovers during training camp. Team loses any MEEK quality and gains AGGRESSIVE• quality (increase to AGGRESSIVE if already AGGRESSIVE•). Ignore if already AGGRESSIVE.",
  "23": "Star linebacker suffers season ending injury in pre-season game! Team loses any STIFF quality and gains SOFT• quality (reduce to SOFT if already SOFT•). Ignore if already SOFT.",
  "24": "Experiment to try new defensive-back as a punt returner pays off! Team gains ELECTRIC quality for Punt Return. Ignore if already ELECTRIC.",
  "25": "Front Office Grade B or higher? Changes to Player Personnel Management help Head Coach build the roster suited to his strategy, increase Head Coach Grade by one grade. Otherwise, no change to Head Coach Grade.",
  "26": "Leading tackler and fumble-creator at odds with coaching staff and is traded during training camp. Team loses any ACTIVE quality and gains PASSIVE• (reduce to PASSIVE if already PASSIVE•). Ignore if already PASSIVE.",
  "31": "Star Running Back suffers season ending injury in pre-season game! Team’s offense strength reduced to average if possible. Team loses any DYNAMIC quality and gains ERRATIC• quality (reduce to ERRATIC if already ERRATIC•).",
  "32": "Last years first-round linebacker draft pick is finally healthy after being out all last season. Team’s defensive strength is increased one half quality (e.g. INEPT• to average, STAUNCH• to STAUNCH). Ignore if already STAUNCH.",
  "33": "Veteran quarterback is cut in favor of high profile rookie! Team’s offense strength increased to PROLIFIC• if possible. Team gains SHAKY quality; ignore if already SHAKY.",
  "34": "SELFISH or MEDDLING ownership? Ownership reduces perks for players and staff in an effort to save costs. Front Office Grade reduced by one grade. Otherwise, no change to Front Office Grade.",
  "35": "Free Agent signing of veteran running back improves ball control. Team loses any CLUMSY quality and gains SECURE• (increase to SECURE if already SECURE•). Ignore if already SECURE.",
  "36": "Front Office Grade C or lower? Contract negotiations with the Head Coach break down, Head Coach very unhappy; lower Head Coach Grade by 2 grades (max D). Otherwise, no change to Head Coach Grade.",
  "41": "Running back is extremely distracted by off-field issues in his personal life. Team loses any SECURE quality and gains CLUMSY• (reduce to CLUMSY if already CLUMSY•). Ignore if already CLUMSY.",
  "42": "New franchise CEO is hired and immediately improves organizational effectiveness. Front Office grade increased by one grade.",
  "43": "Star defensive back suffers season ending injury in training camp! Team loses any AGGRESSIVE quality and gains MEEK• quality (reduce to MEEK if already MEEK•).",
  "44": "Free Agent signing of young linebacker adds “pop” to the defense. Team loses any PASSIVE quality and gains ACTIVE• (increase to ACTIVE if already ACTIVE•). Ignore if already ACTIVE.",
  "45": "Sports-network series on team’s training camp is a critical success, shining a good light on the Head Coach. Head Coach Grade increased by one grade. (max B)",
  "46": "Patriarch of ownership family passes away. His son assumes the owner role, and ownership is now SELFISH. Ignore if ownership already SELFISH.",
  "51": "Head Coach is reported in the media as unhappy with team ownership and team ownership is not happy about the comments. Head Coach is on the Hot Seat!",
  "52": "Off-season LASIK surgery improves quarterback’s vision. Team loses any SHAKY quality and gains RELIABLE• (increase to RELIABLE if already RELIABLE•). Ignore if already RELIABLE.",
  "53": "Star Receiver suffers season ending injury in pre-season game! Team’s offense strength reduced to average if possible. Team loses any DYNAMIC quality and gains ERRATIC• quality (reduce to ERRATIC if already ERRATIC•).",
  "54": "LOYAL or SAVVY ownership? Ownership decides to invest in state-of-the-art training facilities. Front Office Grade increased by one grade. Otherwise, no change to Front Office Grade.",
  "55": "Mid-round running back makes a splash in training camp! Team’s offensive strength is increased one full quality. (e.g. DULL to average, average to PROLIFIC, etc.). Ignore if already PROLIFIC.",
  "56": "Health issues plague the head coach, making it difficult to concentrate on football. Team loses any EFFICIENT or EFFICIENT• quality.",
  "61": "Place-kicker breaks leg in non-football related accident! Free agent replacement has an XP success range of 11-55 and a FG success rating of 11-44.",
  "62": "Free Agent signing of veteran Tight End provides much needed target for the quarterback. Team loses any SHAKY quality and gains RELIABLE• (increase to RELIABLE if already RELIABLE•). Ignore if already RELIABLE.",
  "63": "New defensive scheme has the defense playing at a new level. Team loses any SOFT quality and gains STIFF• quality (increase to STIFF if already STIFF•). Ignore if already STIFF.",
  "64": "He was a track star, but now he’s returning kicks! Team gains the ELECTRIC quality for both Kick Returns and Punt Returns. Ignore if already ELECTRIC.",
  "65": "Rebuilt offensive line is not gelling as a unit. Team loses any SOLID quality and gains POROUS• (reduce to POROUS if already POROUS•). Ignore if already POROUS.",
  "66": "Heavy emphasis on the five-minute offense in training camp pays dividends. Team loses any INEFFICIENT quality and gains EFFICIENT• (increase to EFFICIENT if already EFFICIENT•). Ignore if already EFFICIENT.",
};
